title: My just-the-docs template. 
description: This is needed for an exercise. 
theme: just-the-docs

url: https://magdazaczek.github.io/just-the-docs-template

aux_links:
  Template Repository: https://github.com/magdazaczek/just-the-docs-template

color_scheme: dark

logo: "/images/freelancers-logo.png"
